package zzh.darfing.mycrm.workbench.mapper;

import org.apache.ibatis.annotations.Param;
import org.springframework.web.bind.annotation.RequestParam;
import zzh.darfing.mycrm.workbench.pojo.ClueRemark;
import zzh.darfing.mycrm.workbench.pojo.CustomerRemark;

import java.util.List;

public interface CustomerRemarkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_customer_remark
     *
     * @mbg.generated Tue Oct 11 16:25:22 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_customer_remark
     *
     * @mbg.generated Tue Oct 11 16:25:22 CST 2022
     */
    int insert(CustomerRemark row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_customer_remark
     *
     * @mbg.generated Tue Oct 11 16:25:22 CST 2022
     */
    int insertSelective(CustomerRemark row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_customer_remark
     *
     * @mbg.generated Tue Oct 11 16:25:22 CST 2022
     */
    CustomerRemark selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_customer_remark
     *
     * @mbg.generated Tue Oct 11 16:25:22 CST 2022
     */
    int updateByPrimaryKeySelective(CustomerRemark row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_customer_remark
     *
     * @mbg.generated Tue Oct 11 16:25:22 CST 2022
     */
    int updateByPrimaryKey(CustomerRemark row);

    /*把线索的备注信息转换到客户备注表中一份*/
    int insertCustomerRemarkFromClueRemark(@Param("customerRemarks") List<CustomerRemark> customerRemarks);
}