package zzh.darfing.mycrm.settings.mapper;

import org.apache.ibatis.annotations.Param;
import zzh.darfing.mycrm.settings.pojo.DictionaryType;

import java.util.List;
import java.util.Map;

public interface DictionaryTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbg.generated Sat Oct 08 12:49:47 CST 2022
     */
    int deleteByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbg.generated Sat Oct 08 12:49:47 CST 2022
     */
    int insert(DictionaryType row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbg.generated Sat Oct 08 12:49:47 CST 2022
     */
    int insertSelective(DictionaryType row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbg.generated Sat Oct 08 12:49:47 CST 2022
     */
    DictionaryType selectByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbg.generated Sat Oct 08 12:49:47 CST 2022
     */
    int updateByPrimaryKeySelective(DictionaryType row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbg.generated Sat Oct 08 12:49:47 CST 2022
     */
    int updateByPrimaryKey(DictionaryType row);

    /**
     * 字典类型选择所有
     * 查询所有数据字典类型
     * @return {@link List}<{@link DictionaryType}>
     */
    List<DictionaryType> selectAllDictionaryType();

    /**
     * 更新编辑字典类型
     * 将修改后的字典类型更新到数据库
     * @param dictionaryType 字典类型
     * @return int
     */
    int updateEditDictionaryType(DictionaryType dictionaryType);

    int deleteByCodes(@Param("codes") String[] codes);

    
}