package zzh.darfing.mycrm.settings.mapper;

import org.apache.ibatis.annotations.Param;
import zzh.darfing.mycrm.settings.pojo.DicValue;

import java.util.List;

public interface DicValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbg.generated Sat Oct 08 12:49:47 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbg.generated Sat Oct 08 12:49:47 CST 2022
     */
    int insert(DicValue row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbg.generated Sat Oct 08 12:49:47 CST 2022
     */
    int insertSelective(DicValue row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbg.generated Sat Oct 08 12:49:47 CST 2022
     */
    DicValue selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbg.generated Sat Oct 08 12:49:47 CST 2022
     */
    int updateByPrimaryKeySelective(DicValue row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbg.generated Sat Oct 08 12:49:47 CST 2022
     */
    int updateByPrimaryKey(DicValue row);

    List<DicValue> selectAllDicValue();

    int updateEditDicValue(DicValue dicValue);

    int deleteByIds(@Param("ids") String[] ids);

    List<DicValue> selectAllDicValueByTypeCode(String typeCode);
}